version: "3.3"

services:
  hapi:
    image: ohlaser/hapi-backend:${HAPI_APP_IMAGE_TAG:-latest}
    container_name: "haruka-api"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hapi.rule=Host(`ytwv8sek59ictf9p.oh-laser.com`)"
      - "traefik.http.routers.hapi.entrypoints=websecure"
      - "traefik.http.routers.hapi.tls.certresolver=myresolver"
