version: "3.3"

services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/dynamic.yml"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.httpresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.httpresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.httpresolver.acme.caserver=${LETSENCRYPT_CASERVER}"
      - "--certificatesresolvers.httpresolver.acme.email=soft@oh-laser.com"
      - "--certificatesresolvers.httpresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      CF_API_EMAIL: "soft@oh-laser.com"
      CF_DNS_API_TOKEN: "${CLOUDFLARE_API_KEY}"
    volumes:
      #- "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic.yml:/dynamic.yml"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
