name: Deploy
on: 
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hapi-backend-i
      IMAGE_TAG: $(date +%Y%m%d)
      CONTAINER_NAME: hapi-background
    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # dockerイメージビルドしてレジストリにプッシュ
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      # 本番サーバーにデプロイ
      - name: Deploy to Production Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.PROD_SERVER_SSH_USER }}
          SSH_SERVER: ${{ secrets.PROD_SERVER_ADDRESS }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $SSH_USER@$SSH_SERVER \
            'sudo docker pull $IMAGE_NAME:$IMAGE_TAG \
            && sudo docker stop $CONTAINER_NAME \
            && sudo docker rm $CONTAINER_NAME \
            && sudo docker run -d -p 11080:80 -p 11022:22 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG'

      # フェイルオーバーサーバーにデプロイ
      - name: Deploy to Failover Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FAIL_SERVER_SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.FAIL_SERVER_SSH_USER }}
          SSH_SERVER: ${{ secrets.FAIL_SERVER_ADDRESS }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $SSH_USER@$SSH_SERVER \
            'sudo docker pull $IMAGE_NAME:$IMAGE_TAG \
            && sudo docker stop $CONTAINER_NAME \
            && sudo docker rm $CONTAINER_NAME \
            && sudo docker run -d -p 11080:80 -p 11022:22 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG'

