name: Deploy
on: 
  push:
    branches:
      - deploy
      
env:
  IMAGE_TAG: $(github.sha)
  
jobs:
  # 
  build_and_push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hapi-backend
    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # dockerイメージビルドしてレジストリにプッシュ
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:$IMAGE_TAG


  # 各サーバーに更新を適用
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      SETTING_DIR: /hapi/
      LETSENCRYPT_CASERVER: https://acme-v02.api.letsencrypt.org/directory
    strategy:
      # 並列実行
      matrix:
        SSH_PRIVATE_KEY: [${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}, ${{ secrets.FAIL_SERVER_SSH_PRIVATE_KEY }}]
        SSH_SERVER: [${{ secrets.PROD_SERVER_ADDRESS }}, ${{ secrets.FAIL_SERVER_ADDRESS }}]
        SSH_USER: [${{ secrets.PROD_SERVER_SSH_USER }}, ${{ secrets.FAIL_SERVER_SSH_USER }}]
    
    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      #サーバーにデプロイ ホストマシン設定ファイル
      - name: Deploy to Production Server for host settings
        run: |
          scp -i $SSH_PRIVATE_KEY \
            docker-compose.yml, traefik/traefik.yml \
            $SSH_USER@$SSH_SERVER:$SETTING_DIR

      # サーバーにデプロイ dockerコンテナ
      - name: Deploy to Production Server for docker containers
        run: |
          ssh -i $SSH_PRIVATE_KEY $SSH_USER@$SSH_SERVER << EOF
            cd $SETTING_DIR 
            && HAPI_APP_IMAGE_TAG=$IMAGE_TAG
            && LETSENCRYPT_CASERVER=$LETSENCRYPT_CASERVER
            && docker compose pull
            && docker compose down
            && docker compose up -d
          EOF

