name: Hapi-Push
on: 
  workflow_dispatch:
    inputs:
      devimg:
        description: 'for dev docker image or not'
        required: true
        type: boolean
      
env:
  IMAGE_TAG: ${{ github.sha }}${{ inputs.devimg && '-dev' || '' }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hapi-backend
    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # dockerイメージビルドしてレジストリにプッシュ
      - name: Login to Docker Hub
        run: echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
      - name: Build Docker image
        run: cd app/ && docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME --all-tags 
