name: Traefik-Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SETTING_DIR: /traefik/
      LETSENCRYPT_CASERVER: https://acme-v02.api.letsencrypt.org/directory
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

      PROD_SERVER_SSH_PRIVATE_KEY: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
      PROD_SERVER_ADDRESS: ${{ secrets.PROD_SERVER_ADDRESS }}
      PROD_SERVER_SSH_USER: ${{ secrets.PROD_SERVER_SSH_USER }}
      FAIL_SERVER_SSH_PRIVATE_KEY: ${{ secrets.FAIL_SERVER_SSH_PRIVATE_KEY }}
      FAIL_SERVER_ADDRESS: ${{ secrets.FAIL_SERVER_ADDRESS }}
      FAIL_SERVER_SSH_USER: ${{ secrets.FAIL_SERVER_SSH_USER }}
    strategy:
      # 並列実行
      matrix:
        include:
          - SSH_PRIVATE_KEY: $PROD_SERVER_SSH_PRIVATE_KEY
            SSH_SERVER: $PROD_SERVER_ADDRESS
            SSH_USER: $PROD_SERVER_SSH_USER
          - SSH_PRIVATE_KEY: $FAIL_SERVER_SSH_PRIVATE_KEY
            SSH_SERVER: $FAIL_SERVER_ADDRESS
            SSH_USER: $FAIL_SERVER_SSH_USER

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # ホストキーの登録とsshキーの設定
      - name: Register known hosts
        run: |
          mkdir -p ~/.ssh/ \
          && echo "$KNOWN_HOSTS" | tr -d '\r' > ~/.ssh/known_hosts \
          && echo "${{ matrix.SSH_PRIVATE_KEY }}" | tr -d '\r' > pkey.txt \
          && chmod 600 pkey.txt

      #サーバーにデプロイ ホストマシン設定ファイル
      - name: Deploy to Server for host settings
        run: |
          scp -i pkey.txt -r \
            docker-compose.yml traefik.yml \
            ${{ matrix.SSH_USER }}@${{ matrix.SSH_SERVER }}:$SETTING_DIR

      # サーバーにデプロイ dockerコンテナ
      - name: Deploy to Server for docker containers
        run: |
          ssh -i pkey.txt ${{ matrix.SSH_USER }}@${{ matrix.SSH_SERVER }} << EOF
            cd $SETTING_DIR 
            export LETSENCRYPT_CASERVER=$LETSENCRYPT_CASERVER
            docker compose pull
            docker compose down
            docker compose up -d
          EOF
    
